services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    working_dir: /var/www

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  node:
    image: node:18-alpine
    volumes:
      - ./:/var/www
    working_dir: /var/www
    command: sh -c "npm install && npm run build"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "9090:80"
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root
      - UPLOAD_LIMIT=128M
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    depends_on:
      - mysql
